name: temporal_mixing
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pandas # reading in metadata as dataframe (table with rows and columns)
  - xarray>=0.14.1 # for loading in image data and metadata, plotting
  - rioxarray
  - geocube
  - matplotlib
  - geopandas
  - dask
  - ipykernel
  - scipy
  - pip:
        - porder 
        - datetimerange
